
namespace UsingGeneratedDb
{
    class Program
    {
        //context generated by PM command
        //Scaffold-DbContext "Server=(localdb)\mssqllocaldb; Database=ObjectivesDB; Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer
        static void Main(string[] args)
        {
            ShowDbContent();

            using ObjectivesDbContext db = new();

            Console.WriteLine("\nCreate");
            Objective newObjectiveFirst = new Objective { Name = "NewObjective1", Description = "desc1" };
            Objective newObjectiveSecond = new Objective { Name = "NewObjective2", Description = "desc2" };
            db.Objectives.AddRange(newObjectiveFirst, newObjectiveSecond);
            db.SaveChanges();
            ShowDbContent();

            Console.WriteLine("\nUpdate");
            Objective toUpdate = db.Objectives.Where(x => x.Name == "NewObjective1").FirstOrDefault() ?? throw new NullReferenceException();
            toUpdate.Name += "Updated";
            db.SaveChanges();
            ShowDbContent();

            Console.WriteLine("\nDelete");
            IEnumerable<Objective> toDelete = db.Objectives.Where(x => x.Name.Contains("NewObjective"));
            db.RemoveRange(toDelete);
            db.SaveChanges();
            ShowDbContent();

            Console.ReadKey();
        }

        static void ShowDbContent()
        {
            //read
            using ObjectivesDbContext context = new ObjectivesDbContext();
            var list = context.Objectives.ToList();
            foreach (var item in list) Console.WriteLine($"{item.Id}.{item.Name} - {item.Description}");
        }
    }
}
